server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: none

#idu.security.browser.loginPage 认证登录页面,默认/defaultLogin.html
#idu.security.browser.loginResponseType 认证登录响应方式,默认JSON
idu:
  security:
    browser:
      loginResponseType: JSON
      loginPage: /defaultLogin.html
#imooc.security.code.image.length = 6
#imooc.security.code.image.width = 100
#imooc.security.code.image.url = /user/*