server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: none

#imooc.security.browser.loginPage = /demo-signIn.html
#imooc.security.browser.loginType = REDIRECT

#imooc.security.code.image.length = 6
#imooc.security.code.image.width = 100
#imooc.security.code.image.url = /user/*

